FROM node:22-bookworm
USER root
COPY . /root/sel-manege-frontend
WORKDIR /root/sel-manege-frontend

ARG SEL_MANEGE_EXPRESS_URL
RUN sed -i "s|{{SEL_MANEGE_EXPRESS_URL}}|${SEL_MANEGE_EXPRESS_URL}|g" ./environment/environment.ts

RUN npm install
CMD npm run devstart